spring:
  profiles:
    default: dev

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted

hubu:
  apiurl: "https://sbappstoreapi.ziniao.com"
  appid: "202505061369339710371131392"
  appsecret: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCVYQJ0ziHvoV0oC/Z0c6AuwHWR399p9SgpVD0WfuDSNdc2wsG1Ru3yTEse806S26Ht7MSPpscgVoweCAzdWc1LRc3u8l2lgfrAcKyY/Qr45J5v2YtLg0LUIxg9uTnWJnQ+T2m0EhHXz8LSfkubX3ukEnbKznf1ZY7jSs97oHl7LYvUTcjqkZskwM5fRvhhUhfDyoEc2smRSs8Hv97q1pNvyHmM/KjEBUYOfvHjzle1oSa434dBuwyi8bmqfSiMSzfsNoAN91+ZQ13NM+0uN2yJpPvHJFbNsJAlD74GQvIPDlRV3HamFQLwWzMk94eM7upf4NgncuE9ZtCyUO619FmBAgMBAAECggEADAMPBYGF7RUWvp+no9mgaeIEEkTkXErgfeJOPz7YqU63Dao/lWosvC0yZTy/dsO+k7lUXRDWNl1/SvLuxeXwwjrMwoguy55WIZ9t4aeHeFg5/ViLAPl/KDviOSRp6DSTaGdOYrKJSMdmLTMGtWnKMXlioBBWSR9vjAt5/8D5w9PYPcFaS1gTWXyPcMTyonBWzSxgw6G8ykoRbJPfeEU6hlTTc8ZU4rEk4mXHcoqo9rmyyrGZ9o8tuAAXE9aA3BDtTzCRttS7BdzD+R22IZHFioJ3V2HZOwqTsTuy3/h8FKW8xiSZW7leFaCXaJ/vcnw4h2EITY71PsDnPHPuEvrugQKBgQDTHtOgnV/+AUKsU/jmBQAa4t4VuBSOALMr+H4pib5hXJWf3XuDqoA5xnjNCtL0HySImajA+j5dFJzQ2zKOOo/uEiweyPikew0aWUfO/oz3HjBaa8lJhfjXgYOsNwzJOBO/V0We+TsU7kESb7b1/8V/PoS/TtQSQWiMEJAv3ivTuQKBgQC1IjY+nPBj1tfCxNmEKEu1sEoUJi7YwhlZ3xpDBbxxoogpa2kEy4D89A0MpAcrK+CD3xLLtkix7XRVuPdnxYyWgBUF4IQ6Ko+ORFUUmlhoMXRYmJoTKc29T7urbOxR+loD2kjBUGxAoz9JjPcd6wdErUhLC8JT55Vwk5vmDH0oCQKBgQDMuqscqSBKUGyYcoH+hUDZ0cDtrOn53sHhVQL7QwEkp0TNl1lMkE3yOP4yUFnLtFuYP/I+2S0a1H9Rpg77j9y9UFAKtncwAcfuEkApgf2vMk5PkRDMRKfQTF8k5Ol4Q/IabgYsqKHbpUPjHgR9v7+EqlrOriHHZjh9Ax7f3IIBuQKBgD5Fo8aE5/Q7EXRpfqp7vAObtuwUcHieyl5mYD34g9/BU/SBc9ptKExOjwnwfnJuJELR90FHytg43Yz3CT+I4BuBrziVBoCEz1PG1EVABvLTRb+LvzSlY5EZD1kRGnHYkwfODMNBJeZW+VQM/YwwmBAZTshWI5n6/Rp19NvzITgZAoGAMP8RkdGs8R0z+2Z1q3EOsrNJz80hcDociBiFY2Vxi7YS980SSmeOnVcVyG/4ikqncIpp/bd6X7NPtdDS1GWLH3jz7y+0PDr9rJ4zXHd1bEWiwmxqs0cbilCWuJqHUDT/NMpjRT1t9PijRsh9WbOM1rSoNo1KshfUK2BqbDqvAyU="

sellfox:
  clientId: "368027"
  clientSecret: "2951eb88-f581-48cf-8b8b-8d5c40e37e49"
  getTokenUrl: "https://openapi.sellfox.com/api/oauth/v2/token.json"

logging:
  config: classpath:logback.xml
