### web
server.port=8080
### DevTools settings
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=1s
spring.devtools.restart.quiet-period=400ms

### Additional paths to watch for restart
spring.devtools.restart.additional-paths=src/main/resources/templates,src/main/resources/static

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=Liv88625200@@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
